export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const CREATE_DETAILS_REQUEST = 'CREATE_DETAILS_REQUEST';
export const CREATE_DETAILS_SUCCESS = 'CREATE_DETAILS_SUCCESS';
export const CREATE_DETAILS_FAIL = 'CREATE_DETAILS_FAIL';

export const CREATE_PAY_REQUEST = 'CREATE_PAY_REQUEST';
export const CREATE_PAY_SUCCESS = 'CREATE_PAY_SUCCESS';
export const CREATE_PAY_FAIL = 'CREATE_PAY_FAIL';
export const CREATE_PAY_RESET = 'CREATE_PAY_RESET';


export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'
